nodeLinker: node-modules

npmPublishAccess: restricted

npmRegistries:
  'https://registry.npmjs.org':
    npmAuthToken: '${NPM_TOKEN}'
    
npmScopes:
  shanmukh0504:
    npmRegistryServer: "https://registry.npmjs.org/"
    npmAuthToken: "${NPM_TOKEN}"
